### Registro de Usuarios
POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
	"name": "Kelly",
	"email": "kelly@gmail.com",
	"password": "kelly54321",
	"c_password": "kelly54321"
}

### Autenticacion  (login)
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "kelly@gmail.com",
	"password": "kelly54321"
}

### Perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 3|4pXDTGFL98QQYbpu6F7DeDXIIQvXYmGZ5XgvEcp201f78542

### Salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 3|4pXDTGFL98QQYbpu6F7DeDXIIQvXYmGZ5XgvEcp201f78542
