### listar
GET http://127.0.0.1:8000/api/producto
Accept: application/json
Authorization: Bearer 4|GCSQ0UV3CIJ4bvNS7ql0FdJs2GXJe76oghIEi6x95b504f66

### Guardar producto
POST http://127.0.0.1:8000/api/producto
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|GCSQ0UV3CIJ4bvNS7ql0FdJs2GXJe76oghIEi6x95b504f66

{
    "nombre": "Laptop",
    "precio": 8000,
    "cantidad": 5,
    "categoria_id": 1
}

### mostrar producto
GET http://127.0.0.1:8000/api/producto/1
Authorization: Bearer 15|Lt3CIWPkptDzu3MGv2W80Y26UDnNO9T5A8dkNSK0c86fb0b4

### cambiar estado DELETE
http://127.0.0.1:8000/api/producto/1
Authorization: Bearer 15|Lt3CIWPkptDzu3MGv2W80Y26UDnNO9T5A8dkNSK0c86fb0b4
