POST http://127.0.0.1:8000/api/reset-password
Content-Type: application/json
Accept: application/json

{
    "email": "kelly@mail.com"
}


### Cambio de contraseña
POST http://127.0.0.1:8000/api/change-password
Content-Type: application/json
Accept: application/json

{
    "token": "6|X0zpUSFT4pcTrwWkTgREh5utkkzRHLeHwgsjofIu0cf38e2d",
    "email": "kelly@mail.com",
    "password": "admin54321",
    "password_confirmation": "admin54321"
}
