GET http://127.0.0.1:8000/api/usuario
Authorization: Bearer 28|kN2aAoOBuD62wL9amconmSleb9hRLn6eBu6QG00O97b5e159
### Guardar Usuario
POST http://127.0.0.1:8000/api/usuario
Accept: application/json
Content-Type: application/json
Authorization: Bearer 28|kN2aAoOBuD62wL9amconmSleb9hRLn6eBu6QG00O97b5e159

{
    "name": "Ana",
    "email": "ana@mail.com",
    "password": "ana54321"
}

### mostrar
GET http://127.0.0.1:8000/api/usuario/7
Accept: application/json
Content-Type: application/json
Authorization: Bearer 28|kN2aAoOBuD62wL9amconmSleb9hRLn6eBu6QG00O97b5e159

### Modificar
PUT http://127.0.0.1:8000/api/usuario/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer 28|kN2aAoOBuD62wL9amconmSleb9hRLn6eBu6QG00O97b5e159

{
    "name": "Pedro",
    "email": "pedro@mail.com",
    "password": "pedro54321"
}

### Eliminar
DELETE http://127.0.0.1:8000/api/usuario/4
Accept: application/json
